defaults:
  -
    scope:
      path: "projects"
    values:
      layout: "project"
      
prose:
  metadata:
    projects/_posts:
      - name: "title"
        field:
          element: "text"
          value: "title"
          label: "Title"
